version: '3.9'

services:
    waf:
        container_name: waf_3
        build:
            context: ./waf_3
        image: owasp/modsecurity:3
        depends_on:
            - web
            - db
        volumes:
            - ./waf_3/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
            - ./waf_3/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./waf_3/nginx_conf/modsecurity.conf:/etc/conf.d/modsecurity.conf
            - ./waf_3/modsecurity_conf/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
            - ./waf_3/modsecurity_conf/setup.conf:/etc/modsecurity.d/setup.conf
            - ./waf_3/modsecurity-crs/:/usr/local/modsecurity-crs/
        ports:
            - 80:80
    web:
        build:
            context: ./App1
            dockerfile: Dockerfile
        container_name: app
        depends_on:
            - db
        volumes:
            - ./App1/:/var/www/html/
        ports:
            - 8080:80
    web1:
        build:
            context: ./App2
            dockerfile: Dockerfile
        container_name: app1
        depends_on:
            - db
        volumes:
            - ./App2/:/var/www/html/
        ports:
            - 8081:80
    db:
        container_name: appdb
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass